### ISSUE TITLE
Mizoram

### ISSUE THREAD

**Issue by justinelliotmeyers** [justinelliotmeyers/India_Official_Boundaries_2019#2]
https://en.wikipedia.org/wiki/List_of_districts_of_Mizoram

lgd does not support:
![image](https://user-images.githubusercontent.com/5324316/77852363-42f6b700-71ac-11ea-82c5-81389faa992c.png)

**Comment by aadityadar** [comment]
that's odd, https://lgdirectory.gov.in/ shows me 11 districts here: 
![image](https://user-images.githubusercontent.com/6592655/77854818-225d4a00-720a-11ea-8a1a-5fa0c22ed122.png)

here are the new districts:
- hnahthial (parent: lunglei) 
- saitual (parent: aizwal, champhai) 
- khawzawl (parent: champhai, serchhip)

confirmed from rbi circular 
https://www.rbi.org.in/scripts/NotificationUser.aspx?Id=11726&Mode=0

![image](https://user-images.githubusercontent.com/6592655/77855074-cb587480-720b-11ea-8eff-7aca830eac6d.png)

**Comment by justinelliotmeyers** [comment]
@aadityadar have you seen maps anywhere? I cannot find any to reference to update. please let me know and i will update asap. Thanks!

**Comment by aadityadar** [comment]
nope, i couldn't find. @torsha1203 came across this https://www.virthli.in/2019/08/shc-huomsunga-khuo-4-saitual-district.html and @esyasi found all by 1 district from osm (which i understand has accuracy issues). you could consider creating two set of shapefiles, a precise one which is incomplete but accurate and an imperfect one which can be used for visualization purposes at least.

**Comment by justinelliotmeyers** [comment]
@aadityadar the boundaries for districts here are better quality: http://www.nedrp.gov.in/ but they aren't the new boundaries. I don't want to get out of scope with updating the data here, but would like better resolution data if we can get it. 

The osm data is amazing and a great resource, but I am basing this data off of 100% official govt data and resources. Chennai is a bit of of whack, but I'd like to minimize putting in other things like that if possible. 

Is it possible to RTI the SOI for a map of districts for MZ? they will not do it for me as I amnot a citizen, but perhaps you could call and ask? Worst case they say no, but until we ask, we won't know!?  Really appreciate your help.

Justin

**Comment by aadityadar** [comment]
Justin, I tried contacting North Eastern District Resources Plan and also Mizoram Remote Sensing Application Centre https://mirsac.mizoram.gov.in/ but no one answered calls. Offices might be shut due to the lockdown. I have never used a RTI for SOI maps, perhaps @devdattaT knows?

**Comment by justinelliotmeyers** [comment]
@aadityadar I will look for maps again tonight. Somewhat of a difficult state to find data for. Not sure if a university there or any govt office could help? Like you stated, it will be difficult during lockdown.

**Comment by aadityadar** [comment]
checked http://www.surveyofindia.gov.in/pages/display/189-open-series-maps(osm) - not helpful
checked http://www.surveyofindia.gov.in/pages/display/117-state-maps "to be released soon"
checked http://mizorural.nic.in/file/BADP/Map%20of%20Mizoram%20Border%20Blocks/Mizoram%20Map.pdf looks like a somewhat useful map but is it 2011 boundary (justin, you would know by comparing with the subdistrict file)
can't find any other maps, will find out if we can get some link at an university or govt office

**Comment by justinelliotmeyers** [comment]
@aadityadar please review updates aligned according to map here:
![IMG-20190810-WA0092](https://user-images.githubusercontent.com/5324316/79142139-07054980-7d89-11ea-90d8-ba58aafee859.jpg)

please let me know what codes should be used.

data is here:
![india](https://user-images.githubusercontent.com/5324316/79142352-5c415b00-7d89-11ea-94e0-ac64c73f0b37.png)

**Comment by aadityadar** [comment]
looks good, visually matches the map that @torsha1203 found. please change lgd codes to:
- hnahthial (DIST_LGD = 726)
- saitual (DIST_LGD = 727)
- khawzawl (DIST_LGD = 728)
dtcode11 can be 000 for these three districts, consistent with LGD

![image](https://user-images.githubusercontent.com/6592655/79150956-419dcf00-7de7-11ea-8533-b7a1c8efbb4b.png)

**Comment by justinelliotmeyers** [comment]
uploaded new data to main repo. please dl and confirm it is done properly. Thank you for all of the feedback!

**Comment by planemad** [comment]
Found a vector map with the new districts

<img width="741" alt="Screen Shot 2020-06-18 at 10 29 13 AM" src="https://user-images.githubusercontent.com/126868/85033770-53855080-b14f-11ea-9012-989ef365623e.png"><br>https://covid19-mizoram-mirsacmizoram.hub.arcgis.com/

**Comment by justinelliotmeyers** [comment]
@planemad will review! Thank you so much!! Added here if you want to peek: https://github.com/justinelliotmeyers/India_Official_Boundaries_2019/tree/master/OTHER_SOURCE_DATA

**Comment by justinelliotmeyers** [comment]
new data looks great! the current data isn't far off. Will update with the new official source!! @planemad thanks for sharing!!!! Yellow is current data. Blue is the new data. Tons of detail! Will adjust boundaries for Mizoram, Manipur, Tripura, and Assam.
![hand_traced](https://user-images.githubusercontent.com/5324316/85062330-521b4e80-b176-11ea-8c1e-ec66772b40b7.jpg)
![new](https://user-images.githubusercontent.com/5324316/85062333-52b3e500-b176-11ea-84d8-a27b5fc33954.jpg)

**Comment by justinelliotmeyers** [comment]
@planemad updated boundaries! Thank you for sending the resource. Keep them coming!!
