### ISSUE TITLE
Chhattisgarh

### ISSUE THREAD

**Issue by justinelliotmeyers** [justinelliotmeyers/India_Official_Boundaries_2019#3]
https://en.m.wikipedia.org/wiki/List_of_districts_of_Chhattisgarh

![Screenshot_20200329-111426](https://user-images.githubusercontent.com/5324316/77852812-966a0480-71ae-11ea-8e5f-75da7542f41a.png)

**Comment by aadityadar** [comment]
- actually looks like the formation of the new district: Gaurela-Pendra-Marwahi (parent: bilaspur) was announced in 2019 but it was only officially notified in 2020. so we should not include this in the current shapefile as we are using 31 dec 2019 as the cutoff. 

- there's conflicting news reports available on when the formation of this district was notified. hindi news media [1] says 20 sep 2019 but english news media [2] says 10 feb 2020. a rbi circular [3] clarifies what probably happened : "the Government of Chhattisgarh vide Gazette Notification No. F11-04/2019/Seven-4 dated December 30, 2019 had notified the formation of one new district viz. Gaurela- Pendra-Marwahi in the State of Chhattisgarh with effect from February 10, 2020."

[1] https://www.patrika.com/raipur-news/chhattisgarh-new-district-of-gaurela-pendra-marwahi-made-three-tahsil-5122425/ 

[2] https://www.dailypioneer.com/2020/state-editions/gaurela-pendra-marwahi-is-c---garh---s-28th-district.html

[3] https://m.rbi.org.in/scripts/BS_CircularIndexDisplay.aspx?Id=11830

ps: i am pasting the map here just in case this is useful when we update the boundaries for 2020:
map: https://www.bhaskar.com/chhattisgarh/bilaspur/news/bilaspur-news-5th-part-of-bilaspur-will-be-broken-into-28th-district-of-chhattisgarh-01619475.html 
![image](https://user-images.githubusercontent.com/6592655/77854340-5b47ef80-7207-11ea-97d5-5e3edaea07fe.png)

**Comment by justinelliotmeyers** [comment]
@aadityadar if it did not go into effect until 2020, i will close. please let me know. thanks!

**Comment by aadityadar** [comment]
confirmed, please close this issue.

![image](https://user-images.githubusercontent.com/6592655/78785572-fe95c300-79c4-11ea-8d2e-b8931e396b4a.png)
source: https://rbidocs.rbi.org.in/rdocs/notification/PDFs/NOTI18138A11342DF9A4F91919102C0A4E55FD5.PDF

**Comment by justinelliotmeyers** [comment]
Will update if we decided to go to a full 2020 version.
