### ISSUE TITLE
tamil nadu

### ISSUE THREAD

**Issue by aadityadar** [justinelliotmeyers/India_Official_Boundaries_2019#4]
there were 37 districts in tamil nadu as on 31 dec 2019. the India_District_33 shapefile originally had 32 districts but it was recently updated to include 33 districts. i would suggest reversing the latest change; the new district mayiladuthurai (parent: nagapattinam) that was added was formed in 2020 and if start adding districts from 2020 then we will also have to update other states. we can create a separate file for 2020 boundaries later. 

the five new districts that should be added to tn are: 
- chengalpattu (parent: kancheepuram) https://en.wikipedia.org/wiki/Chengalpattu_district
  - suggested dist_lgd code to 5741
- kallakurichi (parent: villupuram) https://en.wikipedia.org/wiki/Kallakurichi_district
  - suggested dist_ldg code: 729
- ranipet (parent: vellore) https://en.wikipedia.org/wiki/Ranipet_district
  - suggested dist_lgd code: 5951
- tirupathur (parent: vellore) https://en.wikipedia.org/wiki/Tirupathur_district
  - suggested dist_lgd code: 5952
- tenkasi (parent: tirunelveli) https://en.wikipedia.org/wiki/Tenkasi_district
  - suggested dist_lgd code: 5921

**Comment by aadityadar** [comment]
some notifications from tnrd.gov.in (might be useful to figure out how to delimit the subdistricts shapefile) 
[tn-chengalpattu-tnrdgovin.pdf](https://github.com/justinelliotmeyers/India_Official_Boundaries_2019/files/4399203/tn-chengalpattu-tnrdgovin.pdf)
[tn-kallakurichi-tnrdgovin.pdf](https://github.com/justinelliotmeyers/India_Official_Boundaries_2019/files/4399204/tn-kallakurichi-tnrdgovin.pdf)
[tn-tirupathur-tnrdgovin.pdf](https://github.com/justinelliotmeyers/India_Official_Boundaries_2019/files/4399205/tn-tirupathur-tnrdgovin.pdf)
[tn-7districts-tnrdgovin.pdf](https://github.com/justinelliotmeyers/India_Official_Boundaries_2019/files/4399206/tn-7districts-tnrdgovin.pdf)

**Comment by justinelliotmeyers** [comment]
I will dive into these later. reverting mayiladuthurai now. Also adding unique ids to both districts and subdistricts

**Comment by justinelliotmeyers** [comment]
Starting with https://en.wikipedia.org/wiki/Kallakurichi_district
![image](https://user-images.githubusercontent.com/5324316/77863982-30a06b80-71f4-11ea-8eb6-388bbb077884.png)

Georectified the png from the wiki, and it overlaps four current subdistricts. Article states it has six subdistricts: Kallakurichi, Sankarapuram, Chinnasalem, Ulundurpet, Thirukovilur and Kalvarayanmalai. I believe some may be new. Will confirm and align to LGD:

9 | 33 | TAMIL NADU | 729 | 1 | KALLAKURICHI | கள்ளக்குறிச்சி |   | 000



Will find official map to confirm this is the correct area.
OUTDATED: https://www.tn.gov.in/DistrictMap
OUTDATED: https://www.elections.tn.gov.in/Web/TNLA_map.htm
https://viluppuram.nic.in/about-district/maps/ This does not agree with wiki area:
![tn2](https://user-images.githubusercontent.com/5324316/77865237-554c1180-71fb-11ea-85f1-80f1b3f5a51a.png)


https://viluppuram.nic.in/loksabha-election-2019/ map does not agree with either:
![image](https://user-images.githubusercontent.com/5324316/77865463-78c38c00-71fc-11ea-9e71-d555d833c23a.png)


Believe this is her:
https://www.tnpscthervupettagam.com/ta/currentaffairs-detail/%E0%AE%95%E0%AE%B3%E0%AF%8D%E0%AE%B3%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AE%BF%E0%AE%9A%E0%AF%8D%E0%AE%9A%E0%AE%BF-%E0%AE%AE%E0%AE%BE%E0%AE%B5%E0%AE%9F%E0%AF%8D%E0%AE%9F%E0%AE%AE%E0%AF%8D-%E2%80%93-%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D%E0%AE%A8%E0%AE%BE%E0%AE%9F%E0%AF%81?cat=tamilnadu-news

Will build in:
![k_new](https://user-images.githubusercontent.com/5324316/77865928-c6d98f00-71fe-11ea-9b38-003206de12d0.png)

Uploaded new polygon. needs review before insert.

**Comment by justinelliotmeyers** [comment]
two maps align:
![image](https://user-images.githubusercontent.com/5324316/77866197-0a80c880-7200-11ea-8ed2-e3e26d939c13.png)

**Comment by justinelliotmeyers** [comment]
https://kancheepuram.nic.in/local-body-ward-delimitation-2020-chengalpattu-district/#dpw
https://cdn.s3waas.gov.in/s31543843a4723ed2ab08e18053ae6dc5b/uploads/2018/06/2018060830.pdf

cannot find map

**Comment by justinelliotmeyers** [comment]
Tirunelveli split:
https://s36a9aeddfc689c1d0e3b9ccc3ab651bc5.s3waas.gov.in/maps/
cdn.s3waas.gov.in/s36a9aeddfc689c1d0e3b9ccc3ab651bc5/uploads/2020/02/2020021393.pdf

![ttt2](https://user-images.githubusercontent.com/5324316/77868908-c6df8c00-720a-11ea-96cc-5497c45474cf.png)

uploaded main area after split - leftover should be tenkasi . will need to confirm.

**Comment by aadityadar** [comment]
@justinelliotmeyers for chengalpattu, a news article [1] mentions that it has 8 talukas (wikipedia mentions the same list): 
- Thirukkazhikundram  
- Chengalpattu 
- Madurantakam  
- Cheyyur  
- Tiruporur  
- Tambaram  
- Pallavaram  
- Vandalur  (looks like this is mentioned as "ALANDUR" in the map you shared [2])

note: Sholinganallur taluk mentioned in the map you shared [2] doesnt seem to be a part of this C. district. wiki confirms this [3], this would be useful for your subdistrict shapefile; looks like its now part of chennai district.

to be sure, one can overlay the map you shared, after selecting the 8 talukas, with the the maps from tnhighways.gov.in [4]. 


[1] https://www.thehindu.com/news/national/tamil-nadu/palaniswami-inaugurates-chengalpattu-district/article30119335.ece

[2] https://cdn.s3waas.gov.in/s31543843a4723ed2ab08e18053ae6dc5b/uploads/2018/06/2018060830.pdf

[3] https://en.wikipedia.org/wiki/Sholinganallur_taluk doesnt seem to be

[4] https://tnhighways.gov.in/maps/Chengalpattu%20Eng%2010-2019.pdf

**Comment by justinelliotmeyers** [comment]
@aadityadar Chengalpattu is a bit tricky. I am going to put this one on backburner for now. Let me look into ranipet and tirupathur. Then I'll jump back to that. If you have a chance to review kallakurichi and tenkasi, let me know. Tenkasi is the oppopsite end that should be erased/ created.

![image](https://user-images.githubusercontent.com/5324316/77976843-11750d00-72cc-11ea-8bc6-55b9e1662ef0.png)

verified:
![ranipet](https://user-images.githubusercontent.com/5324316/78022634-4a8c9c00-7323-11ea-94f7-010b7e75690f.png)

**Comment by aadityadar** [comment]
okay will look at the those two districts in a bit. let me know the issue with chengalpattu and i will try my best to help. is the issue that you are trying to update subdistrict boundaries too (and one doesnt know what to do with sholinganallur)? for covid19india.org we just need district boundaries and i think it should be possible to do that based on the map you shared https://cdn.s3waas.gov.in/s31543843a4723ed2ab08e18053ae6dc5b/uploads/2018/06/2018060830.pdf

i would say we just create the map based on this government order https://cms.tn.gov.in/sites/default/files/go/revenue_e_428_2019.pdf (and keep sholinganallur taluk in chengalpattu even if it is not right.)

here's the relevant screenshot from the govt order:
![image](https://user-images.githubusercontent.com/6592655/77979854-6bed8800-7323-11ea-951f-274698579fc4.png)

**Comment by aadityadar** [comment]
just checked Tirunelveli_District and Tirunelveli_District, they both look great! thanks for fixing these.

**Comment by justinelliotmeyers** [comment]
@aadityadar Vellore_Trifurcation_Districts.shp uploaded please review when free. Thank you!

**Comment by aadityadar** [comment]
looks good!

**Comment by guneetnarula** [comment]
Great stuff @justinelliotmeyers and @aadityadar, all this will be useful for a long time to come

**Comment by justinelliotmeyers** [comment]
@aadityadar please review TN_2019_UPDATES_V1.shp for final integration

**Comment by aadityadar** [comment]
> @aadityadar please review TN_2019_UPDATES_V1.shp for final integration

i cant find that file. what's the path?

**Comment by justinelliotmeyers** [comment]
should be up:
![image](https://user-images.githubusercontent.com/5324316/78175672-3f239880-7429-11ea-9576-e14353fc9403.png)

![image](https://user-images.githubusercontent.com/5324316/78175708-4ea2e180-7429-11ea-9282-a73050828594.png)

If that does not work, let me know and i can reupload

**Comment by justinelliotmeyers** [comment]
I need to rebuild chengalpattu. sorry about that, i just dropped in the subdistrict, it is clearly not that. Please let me know about the other areas and I will update. Internet is not working the greatest, so might not hear from me until Friday.  Thanks again!

**Comment by justinelliotmeyers** [comment]
currently this subdistrict is in Kancheepuram. Believe it is in Chennai. I uploaded a new working version: Chengalpattu_FINAL_REVIEW.shp
https://en.wikipedia.org/wiki/Alandur_taluk

**Comment by justinelliotmeyers** [comment]
@aadityadar and @guneetnarula final push to find best boundaries to implement for TN created a issue https://github.com/datameet/maps/issues/46 to see if any of the datameet folks can assist. Once I have a better understanding of exactly how to split Kancheepuram/ Chengalpattu and/or Chennai, I will wrap up Tamil Nadu. Sorry this is taking a while, just like to make sure boundaries are accurate.

**Comment by justinelliotmeyers** [comment]
@aadityadar please review v2. Chennai grew by absorbing some of Kancheepuram. I looked for a quality Chennai map for sometime tonight - impossible to find. I emailed their municipal corporation looking for extent boundary - which wiki states districts 100% align with that as of 2018. 

Please let me know your thoughts about the TN_2019_UPDATES_V2.shp

**Comment by aadityadar** [comment]
justin, sorry for the late reply. i just looked at chengalpattu and kancheepuram. that looks good to me. the question about chennai's boundary expanding is an open one and in the absence of maps, let's go ahead with the quote on wiki and finalize TN_2019_UPDATES_V2.shp. We can make a note in the readme that we are not fully confident about this particular district.

**Comment by justinelliotmeyers** [comment]
review final changes and I will push. Thanks @aadityadar

**Comment by justinelliotmeyers** [comment]
@aadityadar have you had a chance to review? Once completed, i will push out. Thanks!

**Comment by guneetnarula** [comment]
@justinelliotmeyers I had a chance to review v2, looks good to me!

**Comment by justinelliotmeyers** [comment]
thank you for all of your help @aadityadar and @guneetnarula  uploaded data. Will work on next issues - please send any official maps when you can if you see issues anywere else!

**Comment by aadityadar** [comment]
@guneetnarula thanks for reviewing and @justinelliotmeyers thanks for all your work!

**Comment by aadityadar** [comment]
justin, we need to update the DIST_LGD code for the new districts in tamil nadu as follows:
- chengalpattu 730 not 5741
- ranipet 731 not 5951
- tirupathur 732 not 5952
- tenkasi 733 not 5921
- kallakurichi 729 is fine (no changed needed)
i don't remember now why i suggested codes different from what lgd has on their website. sorry about that.

**Comment by justinelliotmeyers** [comment]
updated. Thank you for reviewing!

**Comment by planemad** [comment]
Was looking into the Kanchipuram district, from what i can piece together, Alandur and Pallavaram taluks have been reorganised into:
- Kundrathur taluk for Kanchipuram district
- Pallavaram taluk in Chengelpattu district  
- Chennai district

<img width="389" alt="Screen Shot 2020-04-16 at 8 10 39 PM" src="https://user-images.githubusercontent.com/126868/79518222-88c1d500-801e-11ea-973f-60837ce0b9fc.png">

Maybe with the village list of these taluks on LGD and the village shapefiles might be able to piece together the boundaries.

**Comment by justinelliotmeyers** [comment]
@planemad want to create a new issue for this and I can go back and update the boundaries? Just let me know what goes where and I will adjust. Thanks for the feedback!
