### ISSUE TITLE
tn - erode

### ISSUE THREAD

**Issue by aadityadar** [justinelliotmeyers/India_Official_Boundaries_2019#7]
i wasnt sure if i should bring this up but i noticed that boundaries for TN in @esyasi shapefile (in pink) doesn't match for erode district. here's an official map https://cdn.s3waas.gov.in/s3bca82e41ee7b0833588399b1fcd177c7/uploads/2018/06/2018062985.pdf and it seems that the pink boundaries might be correct. _V2 boundaries are in black. can you take a look at this as well? just as a sanity check. thanks!
![image](https://user-images.githubusercontent.com/6592655/78409135-8d51bb00-7626-11ea-9b52-7630f68aa5ba.png)

**Comment by justinelliotmeyers** [comment]
Will review tonight and try to confirm with official maps. Thanks

**Comment by justinelliotmeyers** [comment]
![erode_before](https://user-images.githubusercontent.com/5324316/78451950-893d9180-7656-11ea-99bd-3ccee748aade.png)

aligned and updated. please review.
