### ISSUE TITLE
mentioning state codes in filenames

### ISSUE THREAD

**Issue by aadityadar** [justinelliotmeyers/India_Official_Boundaries_2019#8]
please consider include state names (or at the very least ISO codes [1] for indian states) in the filenames. suggested renaming:

| old name | new name |
| --- | ---  |
| india_district_01.*.zip | india_district_01_JK.*.zip |
| india_district_02.*.zip | india_district_02_HP.*.zip |
| india_district_03.*.zip | india_district_03_PB.*.zip |
| india_district_04.*.zip | india_district_04_CH.*.zip |
| india_district_05.*.zip | india_district_05_UT.*.zip |
| india_district_06.*.zip | india_district_06_HR.*.zip |
| india_district_07.*.zip | india_district_07_DL.*.zip |
| india_district_08.*.zip | india_district_08_RJ.*.zip |
| india_district_09.*.zip | india_district_09_UP.*.zip |
| india_district_10.*.zip | india_district_10_BR.*.zip |
| india_district_11.*.zip | india_district_11_SK.*.zip |
| india_district_12.*.zip | india_district_12_AR.*.zip |
| india_district_13.*.zip | india_district_13_NL.*.zip |
| india_district_14.*.zip | india_district_14_MN.*.zip |
| india_district_15.*.zip | india_district_15_MZ.*.zip |
| india_district_16.*.zip | india_district_16_TR.*.zip |
| india_district_17.*.zip | india_district_17_ML.*.zip |
| india_district_18.*.zip | india_district_18_AS.*.zip |
| india_district_19.*.zip | india_district_19_WB.*.zip |
| india_district_20.*.zip | india_district_20_JH.*.zip |
| india_district_21.*.zip | india_district_21_OR.*.zip |
| india_district_22.*.zip | india_district_22_CT.*.zip |
| india_district_23.*.zip | india_district_23_MP.*.zip |
| india_district_24.*.zip | india_district_24_GJ.*.zip |
| india_district_25.*.zip | india_district_25_DD.*.zip |
| india_district_26.*.zip | india_district_26_DN.*.zip |
| india_district_27.*.zip | india_district_27_MH.*.zip |
| india_district_28.*.zip | india_district_28_AP.*.zip |
| india_district_29.*.zip | india_district_29_KA.*.zip |
| india_district_30.*.zip | india_district_30_GA.*.zip |
| india_district_31.*.zip | india_district_31_LD.*.zip |
| india_district_32.*.zip | india_district_32_KL.*.zip |
| india_district_33_updated_2019.*.zip | india_district_33_TN.*.zip |
| india_district_34.*.zip | india_district_34_PY.*.zip |
| india_district_35.*.zip | india_district_35_AN.*.zip |
| india_district_36.*.zip | india_district_36_TG.*.zip |
| india_district_37.*.zip | india_district_37_LA.*.zip |

[1] https://en.wikipedia.org/wiki/ISO_3166-2:IN#Current_codes

**Comment by justinelliotmeyers** [comment]
RENAMED AND UPLOADED
